### PR TITLE
Updated patchouli book to 1.20 and added it back.

### PR DESCRIPTION
**Pull request by CuddleTheif**
Updated all patchouli compat code to 1.20 and made complie again
Moved patchouli book assets to the resourcepack as per update to patchouli
Added calls to run the old patchouli compat code again to load the book

Resolves https://github.com/lucaargolo/fabric-seasons-extras/issues/14
Resolves https://github.com/lucaargolo/fabric-seasons-extras/issues/17

### CODE REVIEW

**Comment by theavandiepen** [comment]
The only problem I'm running into with this is that it breaks REI. Specifically, REI no longer shows any items whatsoever, which definitely gets in the way of being able to see recipes for various mods, including ones that only have REI compatibility

**Comment by theavandiepen** [comment]
Note: reloading plugins in REI makes items appear again, so it's not completely broken, phew. Please disregard my previous comment

**Comment by Starlightll** [comment]
Works very well, thank you so much

**Comment by bluejorts** [comment]
Is this mod abandoned now? This issue is still present in mainline...

**Pull request merged**
